<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Dps extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Dps_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $dps = $this->Dps_model->get_all();

        $data = array(
            'dpse_data' => $dps
        );

        $this->load->view('dps_list', $data);
    }

    public function read($id) 
    {
        $row = $this->Dps_model->get_by_id($id);
        if ($row) {
            $data = array(
		'ID' => $row->ID,
		'NIK' => $row->NIK,
		'nama_lengkap' => $row->nama_lengkap,
		'tmp_lahir' => $row->tmp_lahir,
		'tgl_lahir' => $row->tgl_lahir,
		'jk' => $row->jk,
		'gol_darah' => $row->gol_darah,
		'agama' => $row->agama,
		'status_perkawinan' => $row->status_perkawinan,
		'ps_alamat' => $row->ps_alamat,
		'ps_rt' => $row->ps_rt,
		'ps_rw' => $row->ps_rw,
		'ps_kelurahan' => $row->ps_kelurahan,
		'ps_kecamatan' => $row->ps_kecamatan,
		'pekerjaan' => $row->pekerjaan,
	    );
            $this->load->view('dps_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('dps'));
        }
    }
    
    public function _rules() 
    {
	$this->form_validation->set_rules('NIK', 'nik', 'trim|required');
	$this->form_validation->set_rules('nama_lengkap', 'nama lengkap', 'trim|required');
	$this->form_validation->set_rules('tmp_lahir', 'tmp lahir', 'trim|required');
	$this->form_validation->set_rules('tgl_lahir', 'tgl lahir', 'trim|required');
	$this->form_validation->set_rules('jk', 'jk', 'trim|required');
	$this->form_validation->set_rules('gol_darah', 'gol darah', 'trim|required');
	$this->form_validation->set_rules('agama', 'agama', 'trim|required');
	$this->form_validation->set_rules('status_perkawinan', 'status perkawinan', 'trim|required');
	$this->form_validation->set_rules('ps_alamat', 'ps alamat', 'trim|required');
	$this->form_validation->set_rules('ps_rt', 'ps rt', 'trim|required');
	$this->form_validation->set_rules('ps_rw', 'ps rw', 'trim|required');
	$this->form_validation->set_rules('ps_kelurahan', 'ps kelurahan', 'trim|required');
	$this->form_validation->set_rules('ps_kecamatan', 'ps kecamatan', 'trim|required');
	$this->form_validation->set_rules('pekerjaan', 'pekerjaan', 'trim|required');

	$this->form_validation->set_rules('ID', 'ID', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Dps.php */
/* Location: ./application/controllers/Dps.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-04-12 13:51:56 */
/* http://harviacode.com */