<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Data_anak extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Data_anak_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $data_anak = $this->Data_anak_model->get_all();

        $data = array(
            'data_anak_data' => $data_anak
        );

        $this->load->view('data_anak_list', $data);
    }

    public function read($id) 
    {
        $row = $this->Data_anak_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id_dataanak' => $row->id_dataanak,
		'id_dataper' => $row->id_dataper,
		'nama_anak' => $row->nama_anak,
		'nomor_akta' => $row->nomor_akta,
		'tgl_akta' => $row->tgl_akta,
	    );
            $this->load->view('data_anak_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('data_anak'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('data_anak/create_action'),
	    'id_dataanak' => set_value('id_dataanak'),
	    'id_dataper' => set_value('id_dataper'),
	    'nama_anak' => set_value('nama_anak'),
	    'nomor_akta' => set_value('nomor_akta'),
	    'tgl_akta' => set_value('tgl_akta'),
	);
        $this->load->view('data_anak_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'id_dataanak' => $this->input->post('id_dataanak',TRUE),
		'id_dataper' => $this->input->post('id_dataper',TRUE),
		'nama_anak' => $this->input->post('nama_anak',TRUE),
		'nomor_akta' => $this->input->post('nomor_akta',TRUE),
		'tgl_akta' => $this->input->post('tgl_akta',TRUE),
	    );

            $this->Data_anak_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('data_anak'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Data_anak_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('data_anak/update_action'),
		'id_dataanak' => set_value('id_dataanak', $row->id_dataanak),
		'id_dataper' => set_value('id_dataper', $row->id_dataper),
		'nama_anak' => set_value('nama_anak', $row->nama_anak),
		'nomor_akta' => set_value('nomor_akta', $row->nomor_akta),
		'tgl_akta' => set_value('tgl_akta', $row->tgl_akta),
	    );
            $this->load->view('data_anak_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('data_anak'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('', TRUE));
        } else {
            $data = array(
		'id_dataanak' => $this->input->post('id_dataanak',TRUE),
		'id_dataper' => $this->input->post('id_dataper',TRUE),
		'nama_anak' => $this->input->post('nama_anak',TRUE),
		'nomor_akta' => $this->input->post('nomor_akta',TRUE),
		'tgl_akta' => $this->input->post('tgl_akta',TRUE),
	    );

            $this->Data_anak_model->update($this->input->post('', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('data_anak'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Data_anak_model->get_by_id($id);

        if ($row) {
            $this->Data_anak_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('data_anak'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('data_anak'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('id_dataanak', 'id dataanak', 'trim|required');
	$this->form_validation->set_rules('id_dataper', 'id dataper', 'trim|required');
	$this->form_validation->set_rules('nama_anak', 'nama anak', 'trim|required');
	$this->form_validation->set_rules('nomor_akta', 'nomor akta', 'trim|required');
	$this->form_validation->set_rules('tgl_akta', 'tgl akta', 'trim|required');

	$this->form_validation->set_rules('', '', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Data_anak.php */
/* Location: ./application/controllers/Data_anak.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-04-13 20:47:58 */
/* http://harviacode.com */