<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Data_perkawinan2_model extends CI_Model
{

    public $table = 'data_perkawinan';
    public $id = 'id_dataper';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
	
	// get field name
	function getField()
    {
        return $this->db->list_fields($this->table);
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_dataper', $q);
	$this->db->or_like('id_ap', $q);
	$this->db->or_like('tgl_pemberkatan', $q);
	$this->db->or_like('hari_lapor', $q);
	$this->db->or_like('tgl_lapor', $q);
	$this->db->or_like('pukul', $q);
	$this->db->or_like('agama', $q);
	$this->db->or_like('nama_organisasi', $q);
	$this->db->or_like('nama_peradilan', $q);
	$this->db->or_like('nomor_putusan', $q);
	$this->db->or_like('tgl_putusan', $q);
	$this->db->or_like('nama_pemuka', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_dataper', $q);
	$this->db->or_like('id_ap', $q);
	$this->db->or_like('tgl_pemberkatan', $q);
	$this->db->or_like('hari_lapor', $q);
	$this->db->or_like('tgl_lapor', $q);
	$this->db->or_like('pukul', $q);
	$this->db->or_like('agama', $q);
	$this->db->or_like('nama_organisasi', $q);
	$this->db->or_like('nama_peradilan', $q);
	$this->db->or_like('nomor_putusan', $q);
	$this->db->or_like('tgl_putusan', $q);
	$this->db->or_like('nama_pemuka', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
	
	

}

/* End of file Data_perkawinan2_model.php */
/* Location: ./application/models/Data_perkawinan2_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-04-19 22:42:34 */
/* http://harviacode.com */