<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Data_perceraianx_model extends CI_Model
{

    public $table = 'data_perceraian';
    public $id = 'id_datacerai';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
	
	// get field name
	function getField()
    {
        return $this->db->list_fields($this->table);
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_datacerai', $q);
	$this->db->or_like('id_ac', $q);
	$this->db->or_like('yang_mengajukan', $q);
	$this->db->or_like('no_akta_perkawinan', $q);
	$this->db->or_like('tgl_akta_perkawinan', $q);
	$this->db->or_like('tmp_pencatatan', $q);
	$this->db->or_like('no_putusan', $q);
	$this->db->or_like('tgl_putusan', $q);
	$this->db->or_like('tkt_peradilan', $q);
	$this->db->or_like('tmp_peradilan', $q);
	$this->db->or_like('nama_lembaga', $q);
	$this->db->or_like('sebab', $q);
	$this->db->or_like('tgl_melapor', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_datacerai', $q);
	$this->db->or_like('id_ac', $q);
	$this->db->or_like('yang_mengajukan', $q);
	$this->db->or_like('no_akta_perkawinan', $q);
	$this->db->or_like('tgl_akta_perkawinan', $q);
	$this->db->or_like('tmp_pencatatan', $q);
	$this->db->or_like('no_putusan', $q);
	$this->db->or_like('tgl_putusan', $q);
	$this->db->or_like('tkt_peradilan', $q);
	$this->db->or_like('tmp_peradilan', $q);
	$this->db->or_like('nama_lembaga', $q);
	$this->db->or_like('sebab', $q);
	$this->db->or_like('tgl_melapor', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
	
	

}

/* End of file Data_perceraianx_model.php */
/* Location: ./application/models/Data_perceraianx_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-04-21 22:13:38 */
/* http://harviacode.com */