<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Akta_perkawinan_model extends CI_Model
{

    public $table = 'akta_perkawinan';
    public $id = 'id_ap';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    function get_all_beetwen($awal,$akhir){
        $qw = "SELECT * FROM akta_perkawinan WHERE tgl_registrasi BETWEEN '$awal' AND '$akhir' ";
        $query = $this->db->query($qw);
                return $query->result();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    function get_all_will($wil,$status)
    {
        $qw = "SELECT * FROM approval 
        JOIN akta_perkawinan ON approval.id_akta=akta_perkawinan.id_ap
        JOIN dps ON akta_perkawinan.nik_pengaju=dps.nik
        WHERE (approval.by_".$status." IS NULL OR approval.by_".$status."='revisi') $wil ORDER BY selesai";
        $query = $this->db->query($qw);
                return $query->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    function get_by_al($id)
    {
        $this->db->where('id_ap', $id);
        return $this->db->get($this->table)->row();
    }
    
     // get data by trisula
    function check($a, $b, $c)
    {
        $query = $this->db->query("SELECT * FROM akta_perkawinan 
            WHERE BINARY no_registrasi = '$a' AND 
            BINARY kode_unik = '$c' AND 
            tgl_registrasi LIKE '$b%'");
                return $query->row();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Akta_perkawinan_model.php */
/* Location: ./application/models/Akta_perkawinan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-04-13 20:47:22 */
/* http://harviacode.com */