<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Data_perceraian_model extends CI_Model
{

    public $table = 'data_perceraian';
    public $id = 'id_datacerai';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
	
	// get field name
	function getField()
    {
        return $this->db->list_fields($this->table);
    }
    
  function get_by_al($id)
    {
        $this->db->where('id_ac', $id);
        return $this->db->get($this->table)->row();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
	
	

}

/* End of file Data_perceraian_model.php */
/* Location: ./application/models/Data_perceraian_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-04-21 19:49:22 */
/* http://harviacode.com */