<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Dps_model extends CI_Model
{

    public $table = 'dps';
    public $id = 'ID';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    function count_all_jk($jk){
            $query = $this->db->query("SELECT * FROM dps WHERE jk='$jk'");
                return $query->result();

        }

    function get_query_data(){
        $query = "SELECT * FROM dps ORDER BY ps_kecamatan ASC";
        $query = $this->db->query($query);
        return $query;
    }

    // get all
    function get_all()
    {
        $this->db->order_by('ps_kecamatan', 'ASC');
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get data by nik
    function get_by_nik($nik)
    {
        $this->db->where('nik', $nik);
        return $this->db->get($this->table)->row();
    }
    
    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where('nik', $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Dps_model.php */
/* Location: ./application/models/Dps_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-04-12 13:51:56 */
/* http://harviacode.com */