<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Pbk_model extends CI_Model
{

    public $table = 'pbk';
    public $id = 'ID';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    
    function get_num(){
        $query = $this->db->query("SELECT COUNT(id) as j_mas from pbk");
        return $query->row();
    }

    function get_rand($limit){
        $query = $this->db->query("SELECT number FROM pbk ORDER BY RAND() LIMIT $limit");
        return $query->result();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
   public function is_kontak_exist($no)
    {
        // cek di database
        $this->db->where('Number', $no);
        $query = $this->db->get('pbk')->num_rows();

        if($query == 0) { return TRUE; }
        else{ return FALSE; }
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Pbk_model.php */
/* Location: ./application/models/Pbk_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-03-15 23:25:21 */
/* http://harviacode.com */